import { Box } from "@chakra-ui/react";
import Head from "next/head";

export const Header = () => {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h3>Burdayım</h3>
    </Box>
  );
};
